opts:
  gpus: [0]
  trainer_config_class: src.configs.trainers.TailorTrainerConfig
trainer:
  target_class: src.trainers.swift_tailor.TailorTrainer

  project_config:
    project_dir: ckpts/swift-tailor/exp2
    
  model:
    target_class: src.models.swift_tailor.SwiftTailor
    dit_config:
      target_class: src.models.base_dit.DiT
      input_size: 512
      patch_size: 16
      in_channels: 3
      hidden_size: 1024
      depth: 28
      num_heads: 16
      mlp_ratio: 4.0
      class_dropout_prob: 0.1
      num_classes: 1000
      learn_sigma: True

  optimizer:
    target_class: torch.optim.AdamW
    lr: 0.0001
    weight_decay: 0

  scheduler:
    target_class: torch.optim.lr_scheduler.StepLR
    step_size: 1
    gamma: 0.999

  dataloader:
    batch_size: 2
    num_workers: 4
    shuffle: True
    pin_memory: True
    drop_last: True
    
    dataset:
      target_class: src.datasets.garmentcode_dataset.GarmentCodeData
      gim_size: 512
      with_snapped_edges: False
      use_official_split: False
      split: 'training'
      split_ratio: 0.9
      